config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :rooms, only: [:index, :show, :new, :create, :destroy] do
    resources :fournitures, only: [:create]
  end
  resources :fournitures, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fourniture.rb
class Fourniture < ApplicationRecord
  belongs_to :room
  validates :name, presence: true, uniqueness: { scope: :room_id }
  validates :image_url, presence: true
  URL_REGEXP = /(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?/ix
  validates :image_url, format: { with: URL_REGEXP, message: 'format invalid' }
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :fournitures, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  validates :banner_url, presence: true
  URL_REGEXP = /(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?/ix
  validates :banner_url, format: { with: URL_REGEXP, message: 'format invalide' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fournitures_controller.rb
class FournituresController < ApplicationController
  def create
    @room = Room.find(params[:room_id])
    @fourniture = Fourniture.new(fourniture_params)
    @fourniture.room = @room
    if @fourniture.save
      redirect_to room_path(@room)
    else
      render 'rooms/show'
    end
  end

  def destroy
    @fourniture = Fourniture.find(params[:id])
    @room = @fourniture.room
    @fourniture.destroy
    redirect_to room_path(@room)
  end

  private

  def fourniture_params
    params.require(:fourniture).permit(:name, :image_url)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    #include fourniture index and new
    @room = Room.find(params[:id])
    @fourniture = Fourniture.new
    @fournitures = @room.fournitures
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)
    if @room.save
      redirect_to room_path(@room)
    else
      render :new
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    redirect_to rooms_path
  end

  private

  def room_params
    params.require(:room).permit(:name, :banner_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFlat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <!-- Hotjar Tracking Code for http://www.bienvenue-futur-appartement123.xyz/ -->
    <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:2625004,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>
    <%= favicon_link_tag %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <div class="content-wrapper">
    <%= yield %>
  </div>
  <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path('home_banner.jpg') %>)">
  <div class="container">
    <h1>Mon futur appartement</h1>
    <p>Gérez les différentes pièces et meubles de votre futur appartement</p>
    <%= link_to "Découvrez toutes les pièces", rooms_path, class: "btn btn-flat" %>
  </div>
</div>

app/views/rooms/_furniture_card.html.erb
<div class="card-furniture" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= fourniture.image_url %>)">
  <%= fourniture.name %>
  <%# <%= link_to "+", fourniture_path(fourniture), method: :delete, data: { confirm: "Are you sure?" }, class: "card-remove-link" %>
  <%= link_to fourniture_path(fourniture), method: :delete, data:{confirm: "Etes vous sûr de vouloir supprimer ce meuble?"}, class: "card-remove-link" do %>
    <p><i class="fas fa-trash-alt pl-1"></i></p>
  <% end %>
</div>

app/views/rooms/_room_card.html.erb
<%= link_to room_path(room) do %>
  <div class="card-room">
    <%= image_tag room.banner_url %>
    <div class="card-room-infos">
      <div>
        <h2><%= room.name %></h2>
      </div>
    </div>
  </div>
<% end %>

app/views/rooms/index.html.erb
<div class="section">
    <h2 class="text-center">Toutes les pièces</h2>
    <div class="cards">
      <% @rooms.each do |room| %>
        <%= render "room_card", room: room %>
      <% end %>
    </div>
  </div>

app/views/rooms/new.html.erb
<div class="content-wrapper" style="background-image: linear-gradient(rgba(245, 246, 252, 0.3),rgba(245, 246, 252, 0.3)), url('https://images.unsplash.com/photo-1602595688238-9fffe12d5af3?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fHJvb218ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=600&q=60');">
  <div class="pt-20 container">
    <h1 class="text-center">Ajouter une nouvelle pièce</h1>
    <div class="row justify-content-center form-body">
      <div class="col-6">
        <%= simple_form_for(@room) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

          <div class="form-inputs">
            <%= f.input :name, label: "Nom" %>
            <%= f.input :banner_url, label: "Url de l'image associée" %>
          </div>

          <div class="form-actions">
            <%= f.submit "Ajouter", class: "btn btn-sub" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= @room.banner_url %>');">
  <div class="container">
    <h1><%= @room.name %></h1>
  </div>
</div>

<div class="pt-30 container">
  <div class="cards">
    <% @room.fournitures.each do |fourniture| %>
      <%= render "rooms/furniture_card", fourniture: fourniture %>
    <% end %>
  </div>
  <div class="pt-30 row justify-content-center">
    <div class="col-12 col-md-4">
      <h4 class="text-center">Ajouter un meuble</h4>
      <%= simple_form_for [ @room, @fourniture ] do |f| %>
        <%= f.input :name, label: "Nom", placeholder: "Table" %>
        <%= f.input :image_url, label: "Url de l'image associée", placeholder: "https://some_nice_image_found_on_google.jpg" %>
        <div class="form-actions">
          <%= f.submit "Ajouter", class: "btn btn-sub" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top" id="navbar-size">

  <%= link_to root_path do %>
    <img class="logo" src="<%= image_path("rentaplush.jpg")%>"/>
  <% end %>

  <%# <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button> %>
<%#
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="search">
    <%= form_tag plushes_path, method: :get, class: "form-inline" do %>
          <%# <%= text_field_tag :query,
            params[:query],
            class: "form-control mr-sm-2",
            placeholder: "Chercher une peluche"%>
          <%# <% end %>
      <%# </form>
    </div> %>
    <div>
      <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Ajouter des pièces', new_room_path, class:"nav-link"%>
      </li>
      </ul>
    </div>
    <div>
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">

        <%= link_to 'Home', root_path, class:"nav-link"%>
      </li>
      <li class="nav-item dropdown">
        <%# <% if current_user %>
          <%# <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= image_path("avatar.jpg")%>
          <%# <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Mon compte</a>
            <%= link_to "Me déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>

          <%# </div>
        <% else %>
          <%# <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="<%= image_path("avatar_signout.jpg")%>
          <%# <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown"> %>
           <%# <%= link_to "Me connecter",  new_user_session_path, class: "dropdown-item" %>
          <%# </div>
        <% end %>
      </li>
    </ul>
    </div>
  </div>
</div>